import GonPhoto from "../assets/driverAssets/driverPhotos/gon.png";
import LuffyPhoto from "../assets/driverAssets/driverPhotos/luffy.png";
import MidoriyaPhoto from "../assets/driverAssets/driverPhotos/midoriya.png";
import KilluaPhoto from "../assets/driverAssets/driverPhotos/killua.png";
import KawakiPhoto from "../assets/driverAssets/driverPhotos/kawaki.png";
import ShikamaruPhoto from "../assets/driverAssets/driverPhotos/shikamaru.png";
import GonMinibusPhoto from "../assets/driverAssets/minisbusAssets/gonBus.jpeg";
import KawakiMinibusPhoto from "../assets/driverAssets/minisbusAssets/kawakiBus.jpeg";
import KilluaMinibusPhoto from "../assets/driverAssets/minisbusAssets/killuaBus.jpeg";
import LuffyMinibusPhoto from "../assets/driverAssets/minisbusAssets/luffyBus.webp";
import MidoriyaMinibusPhoto from "../assets/driverAssets/minisbusAssets/midoriyaBus.jpeg";
import ShikamaruMinibusPhoto from "../assets/driverAssets/minisbusAssets/shikamaruBus.jpeg";

export const drivers = [
  {
    id: "1",
    fullName: "Gon Keita",
    nickname: "Gajo",
    departTime: "10:00",
    arrivalTime: "11:50",
    rate: 5,
    photoPath: GonPhoto,
    minibusPhoto: GonMinibusPhoto,
    minibus: "ST-00-CX",
    seats: [
      { id: "1", booked: false },
      { id: "2", booked: true },
      { id: "3", booked: false },
      { id: "4", booked: false },
      { id: "5", booked: false },
      { id: "6", booked: true },
      { id: "7", booked: true },
      { id: "8", booked: false },
      { id: "9", booked: true },
      { id: "10", booked: false },
      { id: "11", booked: false },
      { id: "12", booked: true },
      { id: "13", booked: false },
      { id: "14", booked: false },
    ],
  },
  {
    id: "2",
    fullName: "Luffy Koffi",
    nickname: "Paxenxa",
    minibus: "ST-05-SI",
    departTime: "11:00",
    arrivalTime: "12:50",
    rate: 5,
    photoPath: LuffyPhoto,
    minibusPhoto: LuffyMinibusPhoto,
    seats: [
      { id: "1", booked: false },
      { id: "2", booked: false },
      { id: "3", booked: false },
      { id: "4", booked: false },
      { id: "5", booked: false },
      { id: "6", booked: true },
      { id: "7", booked: true },
      { id: "8", booked: false },
      { id: "9", booked: true },
      { id: "10", booked: true },
      { id: "11", booked: true },
      { id: "12", booked: true },
      { id: "13", booked: false },
      { id: "14", booked: false },
    ],
  },
  {
    id: "3",
    fullName: "Midoriya Cabral",
    nickname: "Azete",
    minibus: "ST-10-XK",
    departTime: "12:00",
    arrivalTime: "13:50",
    rate: 5,
    photoPath: MidoriyaPhoto,
    minibusPhoto: MidoriyaMinibusPhoto,
    seats: [
      { id: "1", booked: false },
      { id: "2", booked: false },
      { id: "3", booked: false },
      { id: "4", booked: false },
      { id: "5", booked: false },
      { id: "6", booked: false },
      { id: "7", booked: true },
      { id: "8", booked: false },
      { id: "9", booked: false },
      { id: "10", booked: false },
      { id: "11", booked: false },
      { id: "12", booked: false },
      { id: "13", booked: false },
      { id: "14", booked: false },
    ],
  },
  {
    id: "4",
    fullName: "Killua Abdalla",
    nickname: "Ká",
    minibus: "ST-21-CL",
    departTime: "14:00",
    arrivalTime: "15:50",
    rate: 5,
    photoPath: KilluaPhoto,
    minibusPhoto: KilluaMinibusPhoto,
    seats: [
      { id: "1", booked: false },
      { id: "2", booked: true },
      { id: "3", booked: true },
      { id: "4", booked: false },
      { id: "5", booked: false },
      { id: "6", booked: false },
      { id: "7", booked: true },
      { id: "8", booked: false },
      { id: "9", booked: true },
      { id: "10", booked: true },
      { id: "11", booked: false },
      { id: "12", booked: true },
      { id: "13", booked: true },
      { id: "14", booked: true },
    ],
  },
  {
    id: "5",
    fullName: "Kawaki Kasongo",
    nickname: "Já",
    minibus: "ST-02-DC",
    departTime: "15:00",
    arrivalTime: "16:50",
    rate: 5,
    photoPath: KawakiPhoto,
    minibusPhoto: KawakiMinibusPhoto,
    seats: [
      { id: "1", booked: false },
      { id: "2", booked: true },
      { id: "3", booked: false },
      { id: "4", booked: true },
      { id: "5", booked: true },
      { id: "6", booked: true },
      { id: "7", booked: true },
      { id: "8", booked: false },
      { id: "9", booked: true },
      { id: "10", booked: false },
      { id: "11", booked: false },
      { id: "12", booked: false },
      { id: "13", booked: false },
      { id: "14", booked: false },
    ],
  },
  {
    id: "6",
    fullName: "Shikamaru Abdou ",
    nickname: "Gajo",
    minibus: "ST-00-2X",
    departTime: "13:00",
    arrivalTime: "14:50",
    rate: 5,
    photoPath: ShikamaruPhoto,
    minibusPhoto: ShikamaruMinibusPhoto,
    seats: [
      { id: "1", booked: true },
      { id: "2", booked: true },
      { id: "3", booked: false },
      { id: "4", booked: false },
      { id: "5", booked: false },
      { id: "6", booked: true },
      { id: "7", booked: false },
      { id: "8", booked: false },
      { id: "9", booked: false },
      { id: "10", booked: true },
      { id: "11", booked: false },
      { id: "12", booked: true },
      { id: "13", booked: false },
      { id: "14", booked: true },
    ],
  },
];
